### PR TITLE
Check whether to load databases after sync mode check

### LINKED ISSUE #205: rv upgrade fails to resolve if git package present
starting toml file:

```
[project]
name = "test-ldd"
r_version = "4.4"

# any CRAN-type repository, order matters. Additional ability to force source package installation
# Example: {alias = "CRAN", url = "https://cran.r-project.org", force_source = true}
repositories = [
    {alias = "PRISM", url = "https://prism.dev.a2-ai.cloud/rpkgs/snapshots/2025-03-28/"},
]

dependencies = [
  "stringi",
  "maketools",
    "dplyr",
    "rmarkdown",
    "furrr",
    "purrr",
        {name = "tomledit", git = "https://github.com/extendr/tomledit", branch = "main"},

]
```

ran an rv sync which installed all package fine.

```
❯ rv upgrade -vvv
[2025-04-13T11:51:59Z DEBUG rv::r_cmd] R 4.4 found on the path
[2025-04-13T11:51:59Z DEBUG rv::resolver] Didn't find stringi
[2025-04-13T11:51:59Z DEBUG rv::resolver] Didn't find maketools
[2025-04-13T11:51:59Z DEBUG rv::resolver] Didn't find dplyr
[2025-04-13T11:51:59Z DEBUG rv::resolver] Didn't find rmarkdown
[2025-04-13T11:51:59Z DEBUG rv::resolver] Didn't find furrr
[2025-04-13T11:51:59Z DEBUG rv::resolver] Didn't find purrr
[2025-04-13T11:51:59Z DEBUG rv::git::local] Opening git repository at /cluster-data/user-homes/devin/.cache/rv/git/c6f49a107b
[2025-04-13T11:51:59Z DEBUG rv::git::local] Fetching https://github.com/extendr/tomledit with reference Branch("main")
[2025-04-13T11:52:00Z DEBUG rv::git::local] Getting description file content of repo https://github.com/extendr/tomledit at Branch("main") in /cluster-data/user-homes/devin/.cache/rv/git/c6f49a107b
[2025-04-13T11:52:00Z DEBUG rv::git::local] No need to checkout 378e1a2faa084380a2f0d45542049a722a828180, it's already checked out
[2025-04-13T11:52:00Z DEBUG rv::resolver] Didn't find rlang
Failed to resolve all dependencies
    stringi [listed in rproject.toml]
    maketools [listed in rproject.toml]
    dplyr [listed in rproject.toml]
    rmarkdown [listed in rproject.toml]
    furrr [listed in rproject.toml]
    purrr [listed in rproject.toml]
    rlang (>= 1.1.0)  [required by: tomledit]
```

rlang is an imported package for tomledit

```
Package: tomledit
Title: Parse, Read, and Edit 'TOML'
Version: 0.1.1
Authors@R: 
    person("Josiah", "Parry", , "josiah.parry@gmail.com", role = c("aut", "cre"),
           comment = c(ORCID = "0000-0001-9910-865X"))
Description: A toolkit for working with 'TOML' files in R while preserving
    formatting, comments, and structure. 'tomledit' enables serialization of R
    objects such as lists, data.frames, numeric, logical, and date vectors.
License: MIT + file LICENSE
Encoding: UTF-8
Language: en
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.3.2
Config/rextendr/version: 0.3.1.9001
SystemRequirements: Cargo (Rust's package manager), rustc
Depends:
    R (>= 4.2)
Imports: 
    rlang (>= 1.1.0)
URL: https://extendr.github.io/tomledit/, https://github.com/extendr/tomledit
BugReports: https://github.com/extendr/tomledit/issues
```

### PR DESCRIPTION
**Pull request by Keats**
Closes #205

### CODE REVIEW

**Comment by wes-a2ai** [comment]
```
```

```
# Sync with PPM commented out
$ rv -c example_projects/project-upgrade/rproject.toml sync
Nothing to do

# Sync with PPM uncommented
$ rv -c example_projects/project-upgrade/rproject.toml sync
Nothing to do

# Upgrade showing only changed packages
$ rv -c example_projects/project-upgrade/rproject.toml upgrade
- ggplot2
+ ggplot2 (3.5.2, binary from https://packagemanager.posit.co/cran/2025-04-12) in 0ms
- pillar
+ pillar (1.10.2, binary from https://packagemanager.posit.co/cran/2025-04-12) in 0ms
```

File: src/lockfile.rs [hunk 1]
```diff
@@ -323,6 +323,17 @@ impl LockedPackage {
...
+    // check if a resolved_dep has the same name and version
+    fn is_matching_resolved_dep(&self, dep: &ResolvedDependency) -> bool {
+        if self.name == dep.name.as_ref() && 
+            self.version == dep.version.original.to_owned()
+        {
+            true
+        } else {
+            false
+        }
+    }
```
Comment (Keats) [inline src/lockfile.rs]: You can just do 

```
fn is_matching_resolved_dep(&self, dep: &ResolvedDependency) -> bool {
    self.name == dep.name.as_ref() && self.version == dep.version
}
```
It can also be inlined since it's only used once

File: src/main.rs [hunk 2]
```diff
@@ -164,6 +171,20 @@ fn resolve_dependencies(context: &CliContext) -> Vec<ResolvedDependency> {
...
+    if sync_mode == &SyncMode::FullUpgrade && context.lockfile.is_some() {
+        resolution
+            .found
+            .par_iter_mut()
+            .map(|dep| {
+                if context.lockfile.as_ref().unwrap().contains_resolved_dep(dep) {
+                    dep.from_lockfile = true;
+                }
+            })
+            .collect::<Vec<_>>();
```
Comment (Keats) [inline src/main.rs]: can we just create a new vec rather than mutating? I also don't think it's going to be super useful for that to be parallel, did you notice a difference?

File: src/lockfile.rs [hunk 3]
```diff
@@ -481,6 +487,14 @@ impl Lockfile {
         true
     }
 
+    pub fn contains_resolved_dep(&self, dep: &ResolvedDependency) -> bool {
+        self
+            .packages
+            .iter()
+            .find(|x| x.is_matching_resolved_dep(dep))
```
Comment (Keats) [inline src/lockfile.rs]: I meant you could inline it there in the closure

File: src/main.rs [hunk 4]
```diff
@@ -164,7 +171,24 @@ fn resolve_dependencies(context: &CliContext) -> Vec<ResolvedDependency> {
...
+    // If upgrade and there is a lockfile, we want to adjust the resolved dependencies s.t. if the resolved dep has the same
+    // name and version in the lockfile, we say that it was resolved from the lockfile
+    let resolved = if sync_mode == &SyncMode::FullUpgrade && context.lockfile.is_some() {
+        resolution
+            .found
+            .into_iter()
+            .map(|mut dep| {
+                if context.lockfile.as_ref().unwrap().contains_resolved_dep(&dep) {
+                    dep.from_lockfile = true;
+                }
```
Comment (Keats) [inline src/main.rs]: `dep.from_lockfile = context.lockfile.as_ref().unwrap().contains_resolved_dep(&dep);`

File: src/main.rs [hunk 5]
```diff
@@ -176,12 +200,15 @@ fn _sync(
     if !has_logs_enabled {
         context.show_progress_bar();
     }
-    context.load_databases_if_needed()?;
+
+    // If the sync mode is an upgrade, we want to load the databases even if we resolve from the lockfile
```
Comment (Keats) [inline src/main.rs]: if it's an upgrade we won't resolve from the lockfile since it's set to None above right?

File: src/main.rs [hunk 6]
```diff
@@ -132,7 +133,12 @@ enum SyncMode {
 
 /// Resolve dependencies for the project. If there are any unmet dependencies, they will be printed
 /// to stderr and the cli will exit.
-fn resolve_dependencies(context: &CliContext) -> Vec<ResolvedDependency> {
+fn resolve_dependencies<'a>(context: &'a CliContext, sync_mode: &SyncMode) -> Vec<ResolvedDependency<'a>> {
```
Comment (Keats) [inline src/main.rs]: hmm the name SyncMode is weird for something used in the resolution step

File: src/lockfile.rs (hunk 3 above)
Comment (weswc) [reply src/lockfile.rs]: Not completely sure what you mean, but just replaced it with the function body and remove the function

File: src/main.rs (hunk 6 above)
Comment (weswc) [reply src/main.rs]: Went with ResolveMode since its far more about how we're resolving the deps than the sync-ing now. If you have other ideas I'm not particularly attached to it

File: src/main.rs (hunk 5 above)
Comment (weswc) [reply src/main.rs]: Right, right. I was trying to convey even if all packages could be resolved from the lockfile, we don't want to rely on that, so must load the dbs

File: src/lockfile.rs (hunk 3 above)
Comment (Keats) [reply src/lockfile.rs]: That's what i meant yes
