### PR TITLE
Remove jq requirement for install script

### LINKED ISSUE #231: Installation fails for x86_64-linux
When I follow the installation guidelines and use this, I get the following error

```bash
curl -sSL https://raw.githubusercontent.com/A2-ai/rv/refs/heads/main/scripts/install.sh | bash
#> Fetching download URL for x86_64-linux...
#> bash: line 24: jq: command not found
#> Error: Could not find a suitable release asset for your system (x86_64-linux) on GitHub.
#> Please check available assets at https://github.com/a2-ai/rv/releases/latest
```

I have this on my Ubuntu machine
```bash
uname -m
#> x86_64
```

Note that downloading the latest version from releases (v0.6.0 for x86_64 for unknown linux) works!

### PR DESCRIPTION
**Pull request by Keats**
Closes #231

### CODE REVIEW

File: scripts/install.sh [hunk 1]
```diff
@@ -13,14 +13,12 @@ if [ "$arch" = "arm64" ]; then arch="aarch64"; elif [ "$arch" = "x86_64" ]; then
 if [ "$os" = "darwin" ]; then
     os_pattern="apple-darwin"
 else
-    os_pattern=$os
+    os_pattern="unknown-linux-gnu"
```
Comment (Keats) [inline scripts/install.sh:16]: that's going to fail for BSDs but we don't really talk about them in the install docs so it's probably ok

**Review by dpastoor — APPROVED** [review]
thanks!
