### PR TITLE
fix cyclic suggests

### LINKED ISSUE #39: cyclic dep with suggestion/import causes hang
```
[project]
name = "simple"
repositories = [
    {alias = "posit", url = "https://packagemanager.posit.co/cran/2024-12-16/"}
]
dependencies = [
   { name = "dplyr", install_suggestions = true }
]
```

The first install seemed to hang, i thought maybe it was compiling a binary, but the only src detected was postgres which said it was installed

Image

I killed it and tried again and similarly hung

Image

after looking into the plan we see

```
    Lahman=12.0-0 (from posit, type=binary, status=absent)
```

This is a tricky package because it is suggested by dplyr but also imports dplyr.

Throwing some debug statements in showed that lahman was never identified for being able to be installed.

### PR DESCRIPTION
**Pull request by dpastoor**
closes #39

### CODE REVIEW

File: src/package.rs [hunk 1]
```diff
@@ -105,19 +105,27 @@ impl Package {
         self.r_requirement.as_ref()
     }
 
-    pub fn dependencies_to_install(&self, install_suggestions: bool) -> Vec<&Dependency> {
+    pub fn dependencies_to_install(
+        &self,
+        install_suggestions: bool,
+    ) -> (Vec<&Dependency>, Vec<&Dependency>) {
```
Comment (dpastoor) [inline src/package.rs]: i'm not sure if this is should be a struct? - I tried to minimally change things, but tuples always feel harder to track what they're doing/returning

Comment (Keats) [reply src/package.rs]: Probably, i don't know what it is at a glance

File: src/resolver.rs [hunk 2]
```diff
@@ -153,8 +153,32 @@ impl<'d> Resolver<'d> {
...
+                                    // but for now we're going to say no and just let it resolve naturally
+                                    None::<&str>,
+                                    d.version_requirement(),
+                                    false,
+                                    false,
+                                    Some(package.name.as_ref()),
+                                )
+                            })
+                            .collect();
+                        queue.extend(addl_deps);
```
Comment (Keats) [inline src/resolver.rs]: That's exactly the kind of stuff we need tests for. The idea is to push the suggests before the rest of the deps? This also means they are not included in the `ResolvedDependency::dependencies` field and therefore not in the lockfile, is that intended?

Comment (dpastoor) [reply src/resolver.rs]: > This also means they are not included in the ResolvedDependency::dependencies field and therefore not in the lockfile, is that intended?

this should be much clearer in the refactored code. They do make it to the resolved dependencies, they just don't maintain the relationship _as_ dependencies for a given resolved dependency. So we want to add them to the resolution queue, but not connect them to the package as one of its dependencies that prevent the package from being installed until that dep is already installed, else the installation hangs in a deadlock

File: src/package.rs (hunk 1 above)
Comment (dpastoor) [reply src/package.rs]: refactored

File: src/resolver.rs [hunk 3]
```diff
@@ -182,6 +183,26 @@ impl<'d> Resolver<'d> {
...
                         }
                     }
+                    if install_suggestions {
+                        // given all the explicitly called out deps are already in the queue
+                        // we don't need to worry about if this is a copy of one of those values
+                        // since they'll be in front of the queue and will get found/setup for resolution first
+                        // since they're suggested deps we also don't want their suggests for now either,
+                        // though one day we might need to add a recursive suggests akin to deps = TRUE
+                        // for R. This would cover that situation a bit
+                        for d in deps.suggests.unwrap() {
```
Comment (dpastoor) [inline src/resolver.rs:193]: since it doesn't show up in the diff view, this is literally the exact same code at this point as the other dependency queue push_back loop above it for the direct deps

Comment (Keats) [reply src/resolver.rs:193]: That means we have it like 3 times after my branch
